---
spring:
  profiles: local
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: ''
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  h2.console.enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;Mode=Oracle
    
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.comcast: DEBUG
    file: ./log/adCampaign.log